paths:
  data_dir: 'data/'

metadata:
  dx: 5.106500953873407
  dt: 0.0016
  file_duration: 10
  samples_per_file: 6250
  date_start: '2024-05-07'

transforms:
  zscore:
    window: 11
  median: 
    kernel_size: 3
  tv:
    weight: 0.05
  resize:
    width: 500
    height: 500
  clip:
    first_percentile: 1
    last_percentile: 99
  nlm:
    h: 20
    template_window_size: 7
    search_window_size: 35

methods:
  hough:
    threshold1: 50
    threshold2: 200
    rho: 1
    theta: 0.01
    hough_threshold: 120
  hough_prob:
    threshold1: 50
    threshold2: 200
    rho: 1
    theta: 0.01
    hough_threshold: 40
    min_line_length: 80
    max_line_gap: 25

group_lines:
  min_cluster_size: 3

group_segments:
  min_cluster_size: 8
  min_samples: 8
  points_per_segment: 0.3
  rescale_factor: 1
  metric: 'euclidean'

group_all:
  min_cluster_size: 12
  min_samples: 8
  points_per_segment: 0.3
  rescale_factor: 1
  metric: 'euclidean'

clustering:
  n_clusters: 3