paths:
  data_dir: 'data/'

metadata:
  dx: 5.106500953873407
  dt: 0.0016
  file_duration: 10
  samples_per_file: 6250
  date_start: '2024-05-07'

transforms:
  zscore:
    window: 11
  median: 
    kernel_size: 5
  tv:
    weight: 0.05
  resize:
    width: 500
    height: 500

methods:
  hough:
    threshold1: 50
    threshold2: 200
    rho: 1
    theta: 0.01
    hough_threshold: 90

group_lines:
  min_cluster_size: 3
